[package]
name = "snowcap"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"
description = "A simple markup language for iced"
homepage = "https://github.com/boondocklabs/snowcap"
repository = "https://github.com/boondocklabs/snowcap"
readme = "README.md"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.14.0-dev" }
notify = "6.1.1"
pest = "2.7.13"
pest_derive = "2.7.13"
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
